"""Generate README.md, WEIGHTS.md and docs/index.html from the YAML files in data/.

    python scripts/build.py          # validate and write the generated files
    python scripts/build.py --check  # validate and fail if the generated files are out of date (used in CI)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from urllib.parse import quote

import isp_data
from isp_data import ROOT, STATUSES, WEIGHT_STATUSES

GENERATED = '<!-- Generated by scripts/build.py from data/*.yaml. Edit the YAML files, not this file. -->'
RANK = {'weights': 0, 'weights-in-repo': 0, 'code': 1, 'unofficial': 1, 'coming-soon': 2, 'no-code': 2}
TOOL_KINDS = [('raw', 'RAW I/O'), ('isp', 'Classical ISP Pipelines & Algorithms'),
              ('learned', 'Learned-ISP Toolboxes'), ('editor', 'RAW Developers')]


# ---------------------------------------------------------------- helpers
def slug(text: str) -> str:
    """GitHub's heading anchor: lowercase, drop punctuation, spaces to hyphens."""
    s = text.strip().lower()
    s = re.sub(r'[^\w\- ]', '', s)
    return s.replace(' ', '-')


def md(text) -> str:
    """Escape text for use inside a Markdown table cell."""
    s = str(text or '')
    s = s.replace('\\', '\\\\').replace('|', '\\|').replace('*', '\\*').replace('<', '&lt;').replace('>', '&gt;')
    return re.sub(r'\s+', ' ', s).strip()


def link(label, url) -> str:
    return f'[{md(label)}]({url})'


def badge(label, value, color, target):
    lab = quote(label.replace('-', '--').replace('_', '__'))
    val = quote(str(value).replace('-', '--').replace('_', '__'))
    return f'[![{label}](https://img.shields.io/badge/{lab}-{val}-{color})]({target})'


def sort_papers(ps):
    return sorted(ps, key=lambda p: (RANK[p['status']], -p['year'], p['name'].lower()))


def code_cell(p) -> str:
    st, url = p['status'], p.get('code')
    if not url:
        return 'coming soon' if st == 'coming-soon' else '—'
    host = 'GitHub' if 'github.com' in url else 'code'
    label = {'unofficial': f'{host} (unofficial)', 'coming-soon': f'{host} (coming soon)'}.get(st, host)
    out = link(label, url)
    if p.get('framework'):
        out += f"<br><sub>{md(p['framework'])}</sub>"
    return out


def paper_cell(p) -> str:
    out = f"**{link(p['name'], p['paper'])}**"
    if p['title'].strip().lower() != p['name'].strip().lower():
        out += f"<br>{md(p['title'])}"
    sub = md(p['tldr'])
    if p.get('note'):
        sub += f" <i>Note: {md(p['note'])}</i>"
    return out + f'<br><sub>{sub}</sub>'


def weights_cell(p) -> str:
    return '<br>'.join(link(w['label'], w['url']) for w in p.get('weights') or [])


def stats(d):
    ps = [p for _, p in isp_data.all_papers(d)]
    return dict(n=len(ps),
                code=sum(p['status'] in ('weights', 'weights-in-repo', 'code', 'unofficial') for p in ps),
                weights=sum(p['status'] in WEIGHT_STATUSES for p in ps),
                datasets=len(d['datasets']))


# ---------------------------------------------------------------- README
ISP101 = """\
A camera sensor records a noisy, linear mosaic with one color per pixel. The ISP turns it into a display-ready image.
The classical stages below are where learned methods plug in; the [full primer](guide/isp-101.md) explains each stage
and comes with a [50-line NumPy pipeline](guide/minimal_isp.py) you can run on your own RAW files.

```mermaid
flowchart LR
    S[Sensor RAW] --> B[Black level] --> N[Denoise] --> W[White balance] --> D[Demosaic] --> C[Color matrix] --> T[Tone and gamma] --> O[sRGB]
```

| Classical stage | What it does | Learned methods in this list |
|:--|:--|:--|
| Black level, defect pixels, lens shading | remove sensor offsets and optical falloff | usually kept classical |
| Denoising | remove Poisson-Gaussian sensor noise | {denoise} · {lowlight} · {burst} · {video} |
| Demosaicing | interpolate the two missing colors per pixel | {demosaic} |
| White balance | estimate and cancel the illuminant color | {color} |
| Color correction, tone, gamma | map camera RGB to sRGB and compress dynamic range | {color} |
| The whole pipeline | RAW in, sRGB out | {e2e} · {mobile} |
| The pipeline in reverse | sRGB back to RAW | {inverse} |
| Output for machines, not people | detection or segmentation on RAW | {task} |
| Parameters of a hardware ISP | automatic tuning | {tuning} |
"""


def readme(d) -> str:
    cfg, cats, s = d['config'], d['categories'], stats(d)
    pages = f"https://{cfg['owner']}.github.io/{cfg['repo']}/"
    ref = {c['id']: f"[{c['short']}](#{slug(c['title'])})" for c in cats}
    L = [GENERATED, '', '<div align="center">', '',
         f"# {cfg['title']} [![Awesome](https://awesome.re/badge.svg)](https://awesome.re)", '',
         f"**{cfg['tagline']}**", '',
         ' '.join([badge('papers', s['n'], 'blue', '#papers'),
                   badge('with code', s['code'], '0a7bbb', '#papers'),
                   badge('with weights', s['weights'], '2ea44f', 'WEIGHTS.md'),
                   badge('links checked', cfg['checked'], 'lightgrey', '#about-this-list'),
                   badge('license', 'CC0-1.0', 'lightgrey', 'LICENSE'),
                   badge('PRs', 'welcome', 'brightgreen', 'CONTRIBUTING.md')]), '',
         f"**[Interactive page]({pages}) · [Weights index](WEIGHTS.md) · [ISP 101](guide/isp-101.md) · [Contributing](CONTRIBUTING.md)**",
         '', '</div>', '',
         'A curated list of research on neural (learned) camera image signal processors (ISPs). It covers learned replacements for each '
         'stage of the classical pipeline (denoising, demosaicing, white balance, color and tone), end-to-end '
         'RAW-to-sRGB networks, inverse ISPs, ISPs for machine vision, and ISP tuning. For every paper the list records '
         'whether code and pretrained weights are public, and links the weights exactly as the official repository does.',
         '',
         f"It currently holds **{s['n']} papers**, of which **{s['code']} have public code** and **{s['weights']} "
         f"release pretrained weights**, plus {s['datasets']} datasets. The [interactive page]({pages}) has the same "
         'data with search and filters by pipeline stage and weight host.', '',
         '**Reading the tables.** In each section, papers with downloadable weights come first. The *Weights* column '
         'copies the links from each repository README; "in repo" means the checkpoint files are committed to the '
         'repository. In the *Code* column, "unofficial" marks a third-party implementation, "coming soon" a placeholder '
         'repository, and "—" means no public code was found.', '',
         '## Contents', '',
         '- [ISP 101](#isp-101)', '- [Research Threads](#research-threads)', '- [Papers](#papers)']
    for c in cats:
        ps = d['papers'][c['id']]
        nw = sum(p['status'] in WEIGHT_STATUSES for p in ps)
        L.append(f"  - [{c['title']}](#{slug(c['title'])}) ({len(ps)} papers, {nw} with weights)")
    L += ['- [Datasets](#datasets)', '- [Tools & Open-source ISPs](#tools--open-source-isps)',
          '- [Learning Resources](#learning-resources)', '- [Related Lists](#related-lists)',
          '- [Contributing](#contributing)', '- [About This List](#about-this-list)', '- [License](#license)', '',
          '## ISP 101', '', ISP101.format(**ref), '## Research Threads', '']
    for t in d['trends']:
        L.append(f"- **{t['title']}.** {t['text']} <sub>Examples: {md(t['examples'])}</sub>")
    L += ['', '## Papers', '']
    for c in cats:
        ps = sort_papers(d['papers'][c['id']])
        withw = [p for p in ps if p['status'] in WEIGHT_STATUSES]
        rest = [p for p in ps if p['status'] not in WEIGHT_STATUSES]
        L += [f"### {c['title']}", '', c['description'], '']
        if withw:
            L += [f'**With pretrained weights ({len(withw)})**', '',
                  '| Paper | Venue | Code | Weights |', '|:--|:--|:--|:--|']
            L += [f"| {paper_cell(p)} | {md(p['venue'])} {p['year']} | {code_cell(p)} | {weights_cell(p)} |" for p in withw]
            L.append('')
        if rest:
            L += [f'**Code only or not released ({len(rest)})**', '', '| Paper | Venue | Code |', '|:--|:--|:--|']
            L += [f"| {paper_cell(p)} | {md(p['venue'])} {p['year']} | {code_cell(p)} |" for p in rest]
            L.append('')
        L += ['<p align="right"><a href="#contents">back to contents</a></p>', '']
    L += ['## Datasets', '', '| Dataset | Year | Capture | Size | Used for | Link |', '|:--|:--|:--|:--|:--|:--|']
    for x in sorted(d['datasets'], key=lambda x: ([c['id'] for c in cats].index(x.get('task', 'e2e')), -x['year'])):
        L.append(f"| **{md(x['name'])}**<br><sub>{md(x.get('source'))}</sub> | {x['year']} | {md(x.get('capture'))} | "
                 f"{md(x.get('size'))} | {md(x['use'])} | [download]({x['url']}) |")
    L += ['', '## Tools & Open-source ISPs', '']
    for kind, title in TOOL_KINDS:
        items = [t for t in d['tools'] if t.get('kind', 'isp') == kind]
        if not items:
            continue
        L += [f'**{title}**', '']
        L += [f"- [{t['name']}]({t['url']}) - {t['description']}" + (f" <sub>{md(t['language'])}</sub>" if t.get('language') else '')
              for t in items]
        L.append('')
    r = d['resources']
    L += ['## Learning Resources', '', '**Tutorials and surveys**', '']
    L += [f"- [{x['name']}]({x['url']}) - {x['by']}. {x['description']}" for x in r['tutorials']]
    L += ['', '**Books**', '']
    L += [f"- [{x['name']}]({x['url']}) - {x['by']}. {x['description']}" for x in r['books']]
    L += ['', '**Classical papers behind each stage**', '']
    for g in r['classic']:
        L.append(f"- {g['stage']}")
        L += [f"  - [{x['name']}]({x['url']}) - {x['by']}" for x in g['items']]
    L += ['', '## Related Lists', '']
    L += [f"- [{x['name']}]({x['url']}) - {x['description']}" for x in r['related_lists']]
    L += ['', '## Contributing', '',
          'Contributions are welcome: a missing paper, a newly released checkpoint, or a dead link. All content lives in '
          'the YAML files under [`data/`](data/); README.md, WEIGHTS.md and the interactive page are generated from them. '
          'See [CONTRIBUTING.md](CONTRIBUTING.md) for the entry format and the inclusion rules.', '',
          '## About This List', '',
          f"**How entries were collected.** Candidates came from keyword screening of all CVPR, ICCV and WACV papers on CVF "
          "Open Access (2017-2026), the CVF workshops (NTIRE, Mobile AI, MIPI, AIM and others), ECCV 2018-2024 on ECVA, "
          "NeurIPS 2019-2024, reverse-chronological arXiv title searches (raw, bayer, ISP, demosaicing, color constancy, "
          "low-light raw, burst, neural/learned ISP, RGB-to-RAW), and the lists under [Related Lists](#related-lists). "
          "GitHub repository search was used to find code for papers that do not link any.", '',
          f"**How code and weights were checked.** Each repository README (and, where needed, its file tree) was read on "
          f"{cfg['checked']}. The weight links are the ones the README gives, including extraction codes for Baidu Netdisk. "
          "No checkpoint was downloaded or run, and hosted files can disappear; please open an issue or PR when a link "
          "breaks or new weights appear. Checkpoints remain under their authors' licenses.", '',
          '**Known gaps.** ECCV 2026 and NeurIPS 2025 proceedings were not fully available when the list was built. '
          'AAAI, ACM MM, TIP, TPAMI, IJCV and BMVC are covered through arXiv, so journal-only papers may be missing. '
          'Deliberately out of scope: general restoration backbones (SwinIR, Restormer, NAFNet), enhancement or '
          'denoising that only operates on sRGB, RAW-domain NeRF / 3DGS reconstruction, and multispectral or '
          'polarization demosaicing.', '',
          '## License', '',
          '[![CC0](https://licensebuttons.net/p/zero/1.0/88x31.png)](https://creativecommons.org/publicdomain/zero/1.0/)', '',
          'To the extent possible under law, the contributors have waived all copyright and related rights to this work. '
          'See [LICENSE](LICENSE).', '']
    return '\n'.join(L)


# ---------------------------------------------------------------- WEIGHTS.md
def weights_md(d) -> str:
    cfg, s = d['config'], stats(d)
    L = [GENERATED, '', '# Pretrained Weights Index', '',
         f"All {s['weights']} papers in [{cfg['title']}](README.md) that release pretrained weights, grouped by topic. "
         f"Links are copied from each repository README (checked {cfg['checked']}); \"in repo\" means the checkpoint is "
         'committed to the repository.', '']
    for c in d['categories']:
        ps = [p for p in sort_papers(d['papers'][c['id']]) if p['status'] in WEIGHT_STATUSES]
        if not ps:
            continue
        L += [f"## {c['title']}", '', '| Model | Venue | Weights | Code | Framework |', '|:--|:--|:--|:--|:--|']
        for p in ps:
            note = f"<br><sub>{md(p['note'])}</sub>" if p.get('note') else ''
            L.append(f"| **{link(p['name'], p['paper'])}**{note} | {md(p['venue'])} {p['year']} | {weights_cell(p)} | "
                     f"{link('GitHub' if 'github.com' in (p.get('code') or '') else 'code', p['code']) if p.get('code') else '—'} | "
                     f"{md(p.get('framework') or '—')} |")
        L.append('')
    return '\n'.join(L)


# ---------------------------------------------------------------- docs/index.html
SITE_ST = {'weights': 'W', 'weights-in-repo': 'R', 'code': 'C', 'unofficial': 'U', 'coming-soon': 'S', 'no-code': 'N'}


def site(d) -> str:
    cfg, s = d['config'], stats(d)
    P = [dict(n=p['name'], t=p['title'], v=p['venue'], y=p['year'], c=c['id'], s=p['tldr'], p=p['paper'],
              g=p.get('code') or '', st=SITE_ST[p['status']], w=[[w['label'], w['url']] for w in p.get('weights') or []],
              note=p.get('note') or '', fw=p.get('framework') or '') for c, p in isp_data.all_papers(d)]
    D = [[x['name'], x['year'], x.get('source') or '', x.get('capture') or '', x.get('size') or '', x['url'], x['use']]
         for x in d['datasets']]
    CATS = [dict(k=c['id'], name=c['title'], short=c['short'], desc=c['description']) for c in d['categories']]
    TR = [[t['title'], t['text'], t['examples']] for t in d['trends']]
    TOOLS = [[t['name'], t['url'], t['description'], t.get('language') or '', dict(TOOL_KINDS).get(t.get('kind', 'isp'))]
             for t in d['tools']]
    years = [p['y'] for p in P]
    js = lambda x: json.dumps(x, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/')
    tpl = (ROOT / 'scripts' / 'site_template.html').read_text(encoding='utf-8')
    rep = {'__P__': js(P), '__D__': js(D), '__CATS__': js(CATS), '__TRENDS__': js(TR), '__TOOLS__': js(TOOLS),
           '__NP__': str(s['n']), '__NCODE__': str(s['code']), '__NW__': str(s['weights']), '__ND__': str(s['datasets']),
           '__CHECKED__': cfg['checked'], '__TITLE__': cfg['title'], '__TAGLINE__': cfg['tagline'],
           '__REPO_URL__': f"https://github.com/{cfg['owner']}/{cfg['repo']}", '__Y0__': str(min(years)), '__Y1__': str(max(years))}
    for k, v in rep.items():
        tpl = tpl.replace(k, v)
    return tpl


# ---------------------------------------------------------------- main
def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='fail if generated files are out of date')
    args = ap.parse_args()
    d = isp_data.load()
    errs = isp_data.validate(d)
    if errs:
        print('Data validation failed:\n  ' + '\n  '.join(errs))
        sys.exit(1)
    outputs = {ROOT / 'README.md': readme(d), ROOT / 'WEIGHTS.md': weights_md(d), ROOT / 'docs' / 'index.html': site(d)}
    stale = []
    for path, text in outputs.items():
        old = path.read_text(encoding='utf-8') if path.exists() else None
        if args.check:
            if old != text:
                stale.append(str(path.relative_to(ROOT)))
        elif old != text:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding='utf-8')
            print('wrote', path.relative_to(ROOT))
    if stale:
        print('Out of date (run `python scripts/build.py` and commit):', ', '.join(stale))
        sys.exit(1)
    s = stats(d)
    print(f"ok: {s['n']} papers, {s['code']} with code, {s['weights']} with weights, {s['datasets']} datasets")


if __name__ == '__main__':
    main()
